# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'rubocop'

# For plain Ruby scripts
group :development do
  gem 'minitest'
  gem 'rubocop-fjord', require: false
  gem 'rake'
end
